- name: nginx | add key for passenger repos
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7 state=present

- name: nginx | add passenger OSS repo
  apt_repository:
    repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when:  staging is defined or inventory_hostname in groups['errbit']

- name: nginx | Install nginx - Bionic
  apt:
    state: present
    pkg:
      - nginx-common=1.14.0-0ubuntu1.9
      - nginx-extras=1.14.0-0ubuntu1.9
  when: ansible_distribution_release == 'bionic'

- name: nginx | Install nginx extras - Focal
  apt:
    name:
      - nginx
      - nginx-extras
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'focal'

- name: nginx | install nginx passenger OSS packages - Focal
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  loop:
    - { name: python3-passlib, state: present }
    - { name: libnginx-mod-http-passenger, state: present }
    - { name: passenger, state: present }
    - { name: passenger-enterprise, state: absent }
  notify: Restart nginx
  when:
    - ansible_distribution_release == 'focal'
    - staging is defined or inventory_hostname in groups['errbit']

- name: nginx | Install nginx config file
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify:
    - Reload nginx

- name: nginx | Install nginx passenger config file
  template:
    src: templates/passenger.conf
    dest: /etc/nginx/conf.d/passenger.conf
    mode: 0644
  notify:
    - Reload nginx
  tags: passenger

- name: nginx | Install nginx conf for Errbit
  template:
    src: templates/nginx-errbit.conf
    dest: /etc/nginx/conf.d/nginx-errbit.conf
    mode: 0644
  notify: Reload nginx
  tags: nginx_config
  when: inventory_hostname in groups['errbit']

- name: nginx | Remove default nginx server
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/mod-http-passenger.conf
  notify:
    - Reload nginx

- name: nginx | Add nginx logrotate config
  copy:
    src: logrotate-nginx
    dest: /etc/logrotate.d/nginx
