---
- name: install | Install UFW firewall
  apt: package=ufw state=present

- name: conf | Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: restart ufw

- name: conf | Configure ufw settings
  ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name }}"
  with_items:
    - { rule: 'allow', name: 'OpenSSH' }
  notify: restart ufw

- name: ufw | Errbit servers allow port 80 and 443
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 80
    - 443
  when: inventory_hostname in groups['errbit']

- name: ufw | allow incoming CloudWatch monitoring
  ufw:
    rule: allow
    from_ip: "{{ item.ip }}"
    port: "{{ item.port }}"
  with_items:
    - { ip: "71.83.10.72/29", port: 22 }
    - { ip: "66.188.27.86", port: 22 }
    - { ip: "198.199.121.135", port: 22 }
    - { ip: "64.225.46.67", port: 22 }
    - { ip: "159.89.233.198", port: 22 }
  tags: cloudwatch_monitoring

- name: ufw | allow outgoing CloudWatch monitoring
  ufw:
    rule: allow
    to_ip: "159.89.233.198"
    to_port: "8086"
    direction: "out"
  tags: cloudwatch_monitoring

- name: Enable ufw
  ufw: state=enabled
