$ANSIBLE_VAULT;1.1;AES256
32396231343934373766363362323236633662366634626464383238656566626564303564336162
3138353631316333663262373635643432356531323530390a383639613938653439343130303466
62613564396630396234393537656139306337343363356137393132636565646165376632333638
3432336439646165370a353865313632376438366462386130663662646139636432636335333862
38323230656134356534383930323961633232623466666662326237303431303135653764333434
37653738646363396439623236323562613139346434363065386234666638653930633264336330
65643562623330303033633364623265613236363462643631613136643564393330356332656161
64386366623937306536393831623062613562303966616233633038643962383238626131626131
36376238333038336665383234636165643638633865636233313134656234386565663466343363
30396538303533613432663330373362366163636236363064653362663832643634313361323165
63303830353835383063666664313461383835353631616139366565373065353030623862633862
62623033666664343531643432663066646164343661316333666131643635656635386235653432
30343264393238343634353330383034633362343337646331393666323061396431663039643437
39666230313434316163306664346166643131643037393236666462616263623331643163346662
62323336613462646536633865383931643965336134386434316233326436303938326666663965
65656430633235383765633964313635383739613830393265353464353234353264616263383162
34396438313938663839663336373534326438666636393530353836313563393737393137343834
35323361346435343566643163633261303863316337613136373439646531343133626365326538
35363838663439333134303335353561376663613832643033626634623663343830623735393932
38383037386434356134383665333765626566313137616566623437613230663034633563303831
34316533613533623565626461383932663936626165376566666130363965323563643531336661
37656638636130313539303363346463653231653238373333313437643361343566333962666334
32373635656630346630623337363330666338636533323566663866383939663539343636623435
64373766633961346165313564356132353532306262383664343734393839663463653137373834
61333861386664356338663165316439363962373532616565303265366437303130316138363333
30623538646230313839386336333933626164346234323864656137623866323535613130643363
37326430393765613136663963383836303666306363393730613663376461303262323635646638
32363539646363653233
