$ANSIBLE_VAULT;1.1;AES256
35666235306138303830656464386331393762666266343935646334356561326165306337346334
3462373139353464326138393032356433336335333737370a306537613130623564373036303930
66316135616637646166633737316131323335323565303731373938356636306332303164313534
3265666263316262340a376131653566646462396235643666643434616437386131336435643936
32323734656434373031633832396164373832333937393630643237306634306636626565373030
38366334386135626139336438353932633761373764383533303232333862363638383338373530
65363162383162306538633332346135396230376336653034643939616135373766343366633661
33353461336531306131643630316465633963313737346262386630393636323834323261373636
31643363326139666263393363656365306238626635383661643631386466623866643662623962
64323335303137313363636331343466386162336662646337306632346532396239626434303331
373135386562303466306137656563353637
